# Generated by Django 3.0.7 on 2020-08-13 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200812_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 14, 3, 10, 865911)),
        ),
    ]
