# Generated by Django 3.0.7 on 2020-08-29 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200813_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 30, 1, 32, 15, 884243)),
        ),
    ]
