# Generated by Django 3.0.7 on 2020-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%M/%D/'),
        ),
    ]
